// <auto-generated />
using System;
using Lms.Modules.Courses.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lms.Modules.Courses.Infrastructure.Migrations
{
    [DbContext(typeof(CoursesDbContext))]
    [Migration("20260612173622_AddBundleVideosOnly")]
    partial class AddBundleVideosOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("courses")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lms.Modules.Courses.Domain.Bundle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("int");

                    b.Property<bool>("VideosOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Bundles", "courses");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubjectDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BundleId");

                    b.HasIndex("SubjectDefinitionId");

                    b.ToTable("Subjects", "courses");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.SubjectDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("SubjectDefinitions", "courses");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.SubjectDefinitionTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubjectDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SubjectDefinitionId", "UserId")
                        .IsUnique();

                    b.ToTable("SubjectDefinitionTeachers", "courses");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.SubjectSharedUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("SubjectId", "UnitId")
                        .IsUnique();

                    b.ToTable("SubjectSharedUnits", "courses");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.SubjectTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SubjectId", "UserId")
                        .IsUnique();

                    b.ToTable("SubjectTeachers", "courses");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlashcardCount")
                        .HasColumnType("int");

                    b.Property<bool>("HasVideo")
                        .HasColumnType("bit");

                    b.Property<int>("McqCount")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Topics", "courses");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubjectDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubjectDefinitionId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Units", "courses");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.Subject", b =>
                {
                    b.HasOne("Lms.Modules.Courses.Domain.Bundle", "Bundle")
                        .WithMany("Subjects")
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Modules.Courses.Domain.SubjectDefinition", "SubjectDefinition")
                        .WithMany("BatchSubjects")
                        .HasForeignKey("SubjectDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bundle");

                    b.Navigation("SubjectDefinition");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.SubjectDefinitionTeacher", b =>
                {
                    b.HasOne("Lms.Modules.Courses.Domain.SubjectDefinition", "SubjectDefinition")
                        .WithMany("Teachers")
                        .HasForeignKey("SubjectDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjectDefinition");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.SubjectSharedUnit", b =>
                {
                    b.HasOne("Lms.Modules.Courses.Domain.Subject", "Subject")
                        .WithMany("SharedUnitLinks")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Modules.Courses.Domain.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.SubjectTeacher", b =>
                {
                    b.HasOne("Lms.Modules.Courses.Domain.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.Topic", b =>
                {
                    b.HasOne("Lms.Modules.Courses.Domain.Unit", "Unit")
                        .WithMany("Topics")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.Unit", b =>
                {
                    b.HasOne("Lms.Modules.Courses.Domain.SubjectDefinition", "SubjectDefinition")
                        .WithMany("LibraryUnits")
                        .HasForeignKey("SubjectDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lms.Modules.Courses.Domain.Subject", "Subject")
                        .WithMany("Units")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");

                    b.Navigation("SubjectDefinition");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.Bundle", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.Subject", b =>
                {
                    b.Navigation("SharedUnitLinks");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.SubjectDefinition", b =>
                {
                    b.Navigation("BatchSubjects");

                    b.Navigation("LibraryUnits");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Lms.Modules.Courses.Domain.Unit", b =>
                {
                    b.Navigation("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
