services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: lms-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
    ports:
      - "14330:1433"
    volumes:
      - lms-sql-data:/var/opt/mssql

volumes:
  lms-sql-data:
