// <auto-generated />
using System;
using Lms.Modules.SyllabusMentor.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lms.Modules.SyllabusMentor.Infrastructure.Migrations;

[DbContext(typeof(SyllabusMentorDbContext))]
[Migration("20260609120000_AddSyllabusMentor")]
partial class AddSyllabusMentor
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("mentor")
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Lms.Modules.SyllabusMentor.Domain.KnowledgeChunk", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("ChunkIndex")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("SourceId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("SourceTitle")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("nvarchar(300)");

                b.Property<string>("SourceType")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("nvarchar(32)");

                b.Property<Guid?>("SubjectId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("TopicId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("TenantId");

                b.HasIndex("TopicId", "SubjectId");

                b.ToTable("KnowledgeChunks", "mentor");
            });
#pragma warning restore 612, 618
    }
}
